package dev.alvo.html;

import java.util.List;
import java.util.Set;
import java.util.function.BiFunction;

public enum Tags {

  HTML((repr, attr) -> new Tag("html", repr, attr)),
  BODY((repr, attr) -> new Tag("body", repr, attr)),
  H1((repr, attr) -> new Tag("h1", repr, attr)),
  H2((repr, attr) -> new Tag("h2", repr, attr)),
  H3((repr, attr) -> new Tag("h3", repr, attr)),
  H4((repr, attr) -> new Tag("h4", repr, attr)),
  H5((repr, attr) -> new Tag("h5", repr, attr)),
  H6((repr, attr) -> new Tag("h6", repr, attr)),
  TABLE((repr, attr) -> new Tag("table", repr, attr)),
  TABLE_COLUMN((repr, attr) -> new Tag("td", repr, attr)),
  TABLE_ROW((repr, attr) -> new Tag("tr", repr, attr)),
  A((repr, attr) -> new Tag("a", repr, attr)),
  ABBR((repr, attr) -> new Tag("abbr", repr, attr)),
  ACRONYM((repr, attr) -> new Tag("acronym", repr, attr)),
  ADDRESS((repr, attr) -> new Tag("address", repr, attr)),
  APPLET((repr, attr) -> new Tag("applet", repr, attr)),
  AREA((repr, attr) -> new Tag("area", repr, attr)),
  ARTICLE((repr, attr) -> new Tag("article", repr, attr)),
  ASIDE((repr, attr) -> new Tag("aside", repr, attr)),
  AUDIO((repr, attr) -> new Tag("audio", repr, attr)),
  B((repr, attr) -> new Tag("b", repr, attr)),
  BASE((repr, attr) -> new Tag("base", repr, attr)),
  BASEFONT((repr, attr) -> new Tag("basefont", repr, attr)),
  BB((repr, attr) -> new Tag("bb", repr, attr)),
  BDO((repr, attr) -> new Tag("bdo", repr, attr)),
  BIG((repr, attr) -> new Tag("big", repr, attr)),
  BLOCKQUOTE((repr, attr) -> new Tag("blockquote", repr, attr)),
  BR((repr, attr) -> new Tag("br", repr, attr)),
  BUTTON((repr, attr) -> new Tag("button", repr, attr)),
  CANVAS((repr, attr) -> new Tag("canvas", repr, attr)),
  CAPTION((repr, attr) -> new Tag("caption", repr, attr)),
  CENTER((repr, attr) -> new Tag("center", repr, attr)),
  CITE((repr, attr) -> new Tag("cite", repr, attr)),
  CODE((repr, attr) -> new Tag("code", repr, attr)),
  COL((repr, attr) -> new Tag("col", repr, attr)),
  COLGROUP((repr, attr) -> new Tag("colgroup", repr, attr)),
  COMMAND((repr, attr) -> new Tag("command", repr, attr)),
  DATAGRID((repr, attr) -> new Tag("datagrid", repr, attr)),
  DATALIST((repr, attr) -> new Tag("datalist", repr, attr)),
  DD((repr, attr) -> new Tag("dd", repr, attr)),
  DEL((repr, attr) -> new Tag("del", repr, attr)),
  DETAILS((repr, attr) -> new Tag("details", repr, attr)),
  DFN((repr, attr) -> new Tag("dfn", repr, attr)),
  DIALOG((repr, attr) -> new Tag("dialog", repr, attr)),
  DIR((repr, attr) -> new Tag("dir", repr, attr)),
  DIV((repr, attr) -> new Tag("div", repr, attr)),
  DL((repr, attr) -> new Tag("dl", repr, attr)),
  DT((repr, attr) -> new Tag("dt", repr, attr)),
  EM((repr, attr) -> new Tag("em", repr, attr)),
  EMBED((repr, attr) -> new Tag("embed", repr, attr)),
  EVENTSOURCE((repr, attr) -> new Tag("eventsource", repr, attr)),
  FIELDSET((repr, attr) -> new Tag("fieldset", repr, attr)),
  FIGCAPTION((repr, attr) -> new Tag("figcaption", repr, attr)),
  FIGURE((repr, attr) -> new Tag("figure", repr, attr)),
  FONT((repr, attr) -> new Tag("font", repr, attr)),
  FOOTER((repr, attr) -> new Tag("footer", repr, attr)),
  FORM((repr, attr) -> new Tag("form", repr, attr)),
  FRAME((repr, attr) -> new Tag("frame", repr, attr)),
  FRAMESET((repr, attr) -> new Tag("frameset", repr, attr)),
  HEAD((repr, attr) -> new Tag("head", repr, attr)),
  HEADER((repr, attr) -> new Tag("header", repr, attr)),
  HGROUP((repr, attr) -> new Tag("hgroup", repr, attr)),
  HR((repr, attr) -> new Tag("hr", repr, attr)),
  I((repr, attr) -> new Tag("i", repr, attr)),
  IFRAME((repr, attr) -> new Tag("iframe", repr, attr)),
  IMG((repr, attr) -> new Tag("img", repr, attr)),
  INPUT((repr, attr) -> new Tag("input", repr, attr)),
  INS((repr, attr) -> new Tag("ins", repr, attr)),
  ISINDEX((repr, attr) -> new Tag("isindex", repr, attr)),
  KBD((repr, attr) -> new Tag("kbd", repr, attr)),
  KEYGEN((repr, attr) -> new Tag("keygen", repr, attr)),
  LABEL((repr, attr) -> new Tag("label", repr, attr)),
  LEGEND((repr, attr) -> new Tag("legend", repr, attr)),
  LI((repr, attr) -> new Tag("li", repr, attr)),
  LINK((repr, attr) -> new Tag("link", repr, attr)),
  MAP((repr, attr) -> new Tag("map", repr, attr)),
  MARK((repr, attr) -> new Tag("mark", repr, attr)),
  MENU((repr, attr) -> new Tag("menu", repr, attr)),
  META((repr, attr) -> new Tag("meta", repr, attr)),
  METER((repr, attr) -> new Tag("meter", repr, attr)),
  NAV((repr, attr) -> new Tag("nav", repr, attr)),
  NOFRAMES((repr, attr) -> new Tag("noframes", repr, attr)),
  NOSCRIPT((repr, attr) -> new Tag("noscript", repr, attr)),
  OBJECT((repr, attr) -> new Tag("object", repr, attr)),
  OL((repr, attr) -> new Tag("ol", repr, attr)),
  OPTGROUP((repr, attr) -> new Tag("optgroup", repr, attr)),
  OPTION((repr, attr) -> new Tag("option", repr, attr)),
  OUTPUT((repr, attr) -> new Tag("output", repr, attr)),
  P((repr, attr) -> new Tag("p", repr, attr)),
  PARAM((repr, attr) -> new Tag("param", repr, attr)),
  PRE((repr, attr) -> new Tag("pre", repr, attr)),
  PROGRESS((repr, attr) -> new Tag("progress", repr, attr)),
  Q((repr, attr) -> new Tag("q", repr, attr)),
  RP((repr, attr) -> new Tag("rp", repr, attr)),
  RT((repr, attr) -> new Tag("rt", repr, attr)),
  RUBY((repr, attr) -> new Tag("ruby", repr, attr)),
  S((repr, attr) -> new Tag("s", repr, attr)),
  SAMP((repr, attr) -> new Tag("samp", repr, attr)),
  SCRIPT((repr, attr) -> new Tag("script", repr, attr)),
  SECTION((repr, attr) -> new Tag("section", repr, attr)),
  SELECT((repr, attr) -> new Tag("select", repr, attr)),
  SMALL((repr, attr) -> new Tag("small", repr, attr)),
  SOURCE((repr, attr) -> new Tag("source", repr, attr)),
  SPAN((repr, attr) -> new Tag("span", repr, attr)),
  STRIKE((repr, attr) -> new Tag("strike", repr, attr)),
  STRONG((repr, attr) -> new Tag("strong", repr, attr)),
  STYLE((repr, attr) -> new Tag("style", repr, attr)),
  SUB((repr, attr) -> new Tag("sub", repr, attr)),
  SUP((repr, attr) -> new Tag("sup", repr, attr)),
  TBODY((repr, attr) -> new Tag("tbody", repr, attr)),
  TD((repr, attr) -> new Tag("td", repr, attr)),
  TEXTAREA((repr, attr) -> new Tag("textarea", repr, attr)),
  TFOOT((repr, attr) -> new Tag("tfoot", repr, attr)),
  TH((repr, attr) -> new Tag("th", repr, attr)),
  THEAD((repr, attr) -> new Tag("thead", repr, attr)),
  TIME((repr, attr) -> new Tag("time", repr, attr)),
  TITLE((repr, attr) -> new Tag("title", repr, attr)),
  TR((repr, attr) -> new Tag("tr", repr, attr)),
  TRACK((repr, attr) -> new Tag("track", repr, attr)),
  TT((repr, attr) -> new Tag("tt", repr, attr)),
  U((repr, attr) -> new Tag("u", repr, attr)),
  UL((repr, attr) -> new Tag("ul", repr, attr)),
  VAR((repr, attr) -> new Tag("var", repr, attr)),
  VIDEO((repr, attr) -> new Tag("video", repr, attr)),
  WBR((repr, attr) -> new Tag("wbr", repr, attr));

  private final BiFunction<List<TagContentApplicable>, Set<Attribute>, Tag> tagSupplier;

  Tags(BiFunction<List<TagContentApplicable>, Set<Attribute>, Tag> tagSupplier) {
    this.tagSupplier = tagSupplier;
  }

  public BiFunction<List<TagContentApplicable>, Set<Attribute>, Tag> getTagSupplier() {
    return this.tagSupplier;
  }
}
